---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu14.04
    driver:
      box: generic/ubuntu1404
      provider: hyperv
      memory: 2048
      cpus: 2
  - name: ubuntu-16.04
    driver:
      box: generic/ubuntu1604
      provider: hyperv
      memory: 2048
      cpus: 2

suites:
  - name: default
    data_bags_path: "test/integration/data_bags" 
    run_list:
      - recipe[om-env-securitymonkey]
    attributes:
      postgresql:
        password:
          postgres: aVeryStrongPassword
      securitymonkey:
        config:
          fqdn: localhost
          secret_key: aVerySecretKey
          security_password_salt: theSaltiestOfSalts
