name 'om-env-securitymonkey'
maintainer 'Peter Adkins'
maintainer_email 'peter.adkins@kernelpicnic.net'
description 'Installs/Configures a NetFlix Security Monkey environment'
long_description 'Installs/Configures a NetFlix Security Monkey environment'
version '0.2.0'

depends 'apt', '= 6.1.4'
depends 'ntp', '= 3.5.4'
depends 'openssl', '= 7.1.0'
depends 'database', '= 6.1.1'
depends 'postgresql', '= 6.1.1'
depends 'poise-python', '= 1.6.0'
depends 'build-essential', '= 8.0.4'
