name 'securitymonkey'
maintainer 'Peter Adkins'
maintainer_email 'peter.adkins@kernelpicnic.net'
license 'All rights reserved'
description 'Installs/Configures a NetFlix Security Monkey environment'
long_description 'Installs/Configures a NetFlix Security Monkey environment'
version '0.1.0'

depends 'apt', '= 5.0.0'
depends 'ntp', '= 3.2.0'
depends 'openssl', '= 4.4.0'
depends 'database', '= 4.0.6'
depends 'postgresql', '= 3.4.24'
depends 'supervisor', '= 0.4.12'
depends 'poise-python', '= 1.5.1'
depends 'build-essential', '= 7.0.2'
